var searchData=
[
  ['cachedblockinfo_501',['CachedBlockInfo',['../classnet_1_1minecraft_1_1util_1_1_cached_block_info.html',1,'net::minecraft::util']]],
  ['cactusblock_502',['CactusBlock',['../classnet_1_1minecraft_1_1block_1_1_cactus_block.html',1,'net::minecraft::block']]],
  ['cakeblock_503',['CakeBlock',['../classnet_1_1minecraft_1_1block_1_1_cake_block.html',1,'net::minecraft::block']]],
  ['campfireblock_504',['CampfireBlock',['../classnet_1_1minecraft_1_1block_1_1_campfire_block.html',1,'net::minecraft::block']]],
  ['campfirecookingrecipe_505',['CampfireCookingRecipe',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_campfire_cooking_recipe.html',1,'net::minecraft::item::crafting']]],
  ['campfireparticle_506',['CampfireParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_campfire_particle.html',1,'net::minecraft::client::particle']]],
  ['campfiretileentity_507',['CampfireTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_campfire_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['campfiretileentityrenderer_508',['CampfireTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_campfire_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['canapplyatenchantingtable_509',['canApplyAtEnchantingTable',['../classnet_1_1minecraft_1_1enchantment_1_1_enchantment.html#aadd2785edc357d3c7527e49da09caadc',1,'net::minecraft::enchantment::Enchantment']]],
  ['cancatchfire_510',['canCatchFire',['../classnet_1_1minecraft_1_1block_1_1_fire_block.html#a245fac28dbf5979ce17bab599fcf2598',1,'net::minecraft::block::FireBlock']]],
  ['canimatehandpacket_511',['CAnimateHandPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_animate_hand_packet.html',1,'net::minecraft::network::play::client']]],
  ['canyonworldcarver_512',['CanyonWorldCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_canyon_world_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['capelayer_513',['CapeLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_cape_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['carpetblock_514',['CarpetBlock',['../classnet_1_1minecraft_1_1block_1_1_carpet_block.html',1,'net::minecraft::block']]],
  ['carrotblock_515',['CarrotBlock',['../classnet_1_1minecraft_1_1block_1_1_carrot_block.html',1,'net::minecraft::block']]],
  ['cartographycontainer_516',['CartographyContainer',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_cartography_container.html',1,'net::minecraft::inventory::container']]],
  ['cartographytableblock_517',['CartographyTableBlock',['../classnet_1_1minecraft_1_1block_1_1_cartography_table_block.html',1,'net::minecraft::block']]],
  ['cartographytablescreen_518',['CartographyTableScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_cartography_table_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['carvedpumpkinblock_519',['CarvedPumpkinBlock',['../classnet_1_1minecraft_1_1block_1_1_carved_pumpkin_block.html',1,'net::minecraft::block']]],
  ['castingaspellgoal_520',['CastingASpellGoal',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_spellcasting_illager_entity_1_1_casting_a_spell_goal.html',1,'net::minecraft::entity::monster::SpellcastingIllagerEntity']]],
  ['catcollarlayer_521',['CatCollarLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_cat_collar_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['categoryentry_522',['CategoryEntry',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1list_1_1_key_binding_list_1_1_category_entry.html',1,'net::minecraft::client::gui::widget::list::KeyBindingList']]],
  ['catentity_523',['CatEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_cat_entity.html',1,'net::minecraft::entity::passive']]],
  ['catlieonbedgoal_524',['CatLieOnBedGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_cat_lie_on_bed_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['catmodel_525',['CatModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cat_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['catmodel_3c_20net_3a_3aminecraft_3a_3aentity_3a_3apassive_3a_3acatentity_20_3e_526',['CatModel&lt; net::minecraft::entity::passive::CatEntity &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cat_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['catrenderer_527',['CatRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cat_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['catsitonblockgoal_528',['CatSitOnBlockGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_cat_sit_on_block_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['catspawner_529',['CatSpawner',['../classnet_1_1minecraft_1_1world_1_1spawner_1_1_cat_spawner.html',1,'net::minecraft::world::spawner']]],
  ['cattypefix_530',['CatTypeFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_cat_type_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['cauldronblock_531',['CauldronBlock',['../classnet_1_1minecraft_1_1block_1_1_cauldron_block.html',1,'net::minecraft::block']]],
  ['cavedebugrenderer_532',['CaveDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_cave_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['caveedge_533',['CaveEdge',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_cave_edge.html',1,'net::minecraft::world::gen::placement']]],
  ['caveedgeconfig_534',['CaveEdgeConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_cave_edge_config.html',1,'net::minecraft::world::gen::placement']]],
  ['cavespiderentity_535',['CaveSpiderEntity',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_cave_spider_entity.html',1,'net::minecraft::entity::monster']]],
  ['cavespiderrenderer_536',['CaveSpiderRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cave_spider_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['caveworldcarver_537',['CaveWorldCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_cave_world_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['cchatmessagepacket_538',['CChatMessagePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_chat_message_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclickwindowpacket_539',['CClickWindowPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_click_window_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclientsettingspacket_540',['CClientSettingsPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_client_settings_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclientstatuspacket_541',['CClientStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_client_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclosewindowpacket_542',['CCloseWindowPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_close_window_packet.html',1,'net::minecraft::network::play::client']]],
  ['cconfirmteleportpacket_543',['CConfirmTeleportPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_confirm_teleport_packet.html',1,'net::minecraft::network::play::client']]],
  ['cconfirmtransactionpacket_544',['CConfirmTransactionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_confirm_transaction_packet.html',1,'net::minecraft::network::play::client']]],
  ['ccreativeinventoryactionpacket_545',['CCreativeInventoryActionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_creative_inventory_action_packet.html',1,'net::minecraft::network::play::client']]],
  ['ccustompayloadloginpacket_546',['CCustomPayloadLoginPacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_custom_payload_login_packet.html',1,'net::minecraft::network::login::client']]],
  ['ccustompayloadpacket_547',['CCustomPayloadPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_custom_payload_packet.html',1,'net::minecraft::network::play::client']]],
  ['ceditbookpacket_548',['CEditBookPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_edit_book_packet.html',1,'net::minecraft::network::play::client']]],
  ['celebrateraidlossgoal_549',['CelebrateRaidLossGoal',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_abstract_raider_entity_1_1_celebrate_raid_loss_goal.html',1,'net::minecraft::entity::monster::AbstractRaiderEntity']]],
  ['celebrateraidvictorytask_550',['CelebrateRaidVictoryTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_celebrate_raid_victory_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['cenchantitempacket_551',['CEnchantItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_enchant_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cencryptionresponsepacket_552',['CEncryptionResponsePacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_encryption_response_packet.html',1,'net::minecraft::network::login::client']]],
  ['centityactionpacket_553',['CEntityActionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_entity_action_packet.html',1,'net::minecraft::network::play::client']]],
  ['chainblock_554',['ChainBlock',['../classnet_1_1minecraft_1_1block_1_1_chain_block.html',1,'net::minecraft::block']]],
  ['chainedchunkstatuslistener_555',['ChainedChunkStatusListener',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1listener_1_1_chained_chunk_status_listener.html',1,'net::minecraft::world::chunk::listener']]],
  ['chanceconfig_556',['ChanceConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_chance_config.html',1,'net::minecraft::world::gen::placement']]],
  ['chanceplacement_557',['ChancePlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_chance_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['chandshakepacket_558',['CHandshakePacket',['../classnet_1_1minecraft_1_1network_1_1handshake_1_1client_1_1_c_handshake_packet.html',1,'net::minecraft::network::handshake::client']]],
  ['changedimensiontrigger_559',['ChangeDimensionTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_change_dimension_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['changejobtask_560',['ChangeJobTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_change_job_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['changepagebutton_561',['ChangePageButton',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1button_1_1_change_page_button.html',1,'net::minecraft::client::gui::widget::button']]],
  ['channeledlightningtrigger_562',['ChanneledLightningTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_channeled_lightning_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['channelingenchantment_563',['ChannelingEnchantment',['../classnet_1_1minecraft_1_1enchantment_1_1_channeling_enchantment.html',1,'net::minecraft::enchantment']]],
  ['channelmanager_564',['ChannelManager',['../classnet_1_1minecraft_1_1client_1_1audio_1_1_channel_manager.html',1,'net::minecraft::client::audio']]],
  ['charactermanager_565',['CharacterManager',['../classnet_1_1minecraft_1_1util_1_1text_1_1_character_manager.html',1,'net::minecraft::util::text']]],
  ['chargingplayerphase_566',['ChargingPlayerPhase',['../classnet_1_1minecraft_1_1entity_1_1boss_1_1dragon_1_1phase_1_1_charging_player_phase.html',1,'net::minecraft::entity::boss::dragon::phase']]],
  ['chatline_567',['ChatLine',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_chat_line.html',1,'net::minecraft::client::gui']]],
  ['chatoptionsscreen_568',['ChatOptionsScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_chat_options_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['chatscreen_569',['ChatScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_chat_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['chattype_570',['ChatType',['../enumnet_1_1minecraft_1_1util_1_1text_1_1_chat_type.html',1,'net::minecraft::util::text']]],
  ['chatvisibility_571',['ChatVisibility',['../enumnet_1_1minecraft_1_1entity_1_1player_1_1_chat_visibility.html',1,'net::minecraft::entity::player']]],
  ['checkboxbutton_572',['CheckboxButton',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1button_1_1_checkbox_button.html',1,'net::minecraft::client::gui::widget::button']]],
  ['checkerboardbiomeprovider_573',['CheckerboardBiomeProvider',['../classnet_1_1minecraft_1_1world_1_1biome_1_1provider_1_1_checkerboard_biome_provider.html',1,'net::minecraft::world::biome::provider']]],
  ['chelditemchangepacket_574',['CHeldItemChangePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_held_item_change_packet.html',1,'net::minecraft::network::play::client']]],
  ['chestblock_575',['ChestBlock',['../classnet_1_1minecraft_1_1block_1_1_chest_block.html',1,'net::minecraft::block']]],
  ['chestcontainer_576',['ChestContainer',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_chest_container.html',1,'net::minecraft::inventory::container']]],
  ['chestedhorserenderer_577',['ChestedHorseRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_chested_horse_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['chestloottables_578',['ChestLootTables',['../classnet_1_1minecraft_1_1data_1_1loot_1_1_chest_loot_tables.html',1,'net::minecraft::data::loot']]],
  ['chestminecartentity_579',['ChestMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_chest_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['chestscreen_580',['ChestScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_chest_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['chesttileentity_581',['ChestTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_chest_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['chesttileentityrenderer_582',['ChestTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_chest_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['chesttype_583',['ChestType',['../enumnet_1_1minecraft_1_1state_1_1properties_1_1_chest_type.html',1,'net::minecraft::state::properties']]],
  ['chickenentity_584',['ChickenEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_chicken_entity.html',1,'net::minecraft::entity::passive']]],
  ['chickenmodel_585',['ChickenModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_chicken_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['chickenrenderer_586',['ChickenRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_chicken_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['child_587',['Child',['../classnet_1_1minecraft_1_1client_1_1gui_1_1recipebook_1_1_recipe_overlay_gui_1_1_recipe_button_widget_1_1_child.html',1,'net::minecraft::client::gui::recipebook::RecipeOverlayGui::RecipeButtonWidget']]],
  ['childfollownearestadulttask_588',['ChildFollowNearestAdultTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_child_follow_nearest_adult_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['chorusflowerblock_589',['ChorusFlowerBlock',['../classnet_1_1minecraft_1_1block_1_1_chorus_flower_block.html',1,'net::minecraft::block']]],
  ['chorusfruititem_590',['ChorusFruitItem',['../classnet_1_1minecraft_1_1item_1_1_chorus_fruit_item.html',1,'net::minecraft::item']]],
  ['chorusplantblock_591',['ChorusPlantBlock',['../classnet_1_1minecraft_1_1block_1_1_chorus_plant_block.html',1,'net::minecraft::block']]],
  ['chorusplantfeature_592',['ChorusPlantFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_chorus_plant_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['chunk_593',['Chunk',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk.html',1,'net::minecraft::world::chunk']]],
  ['chunkborderdebugrenderer_594',['ChunkBorderDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_chunk_border_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['chunkdistancegraph_595',['ChunkDistanceGraph',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_distance_graph.html',1,'net::minecraft::world::chunk']]],
  ['chunkgenerator_596',['ChunkGenerator',['../classnet_1_1minecraft_1_1world_1_1gen_1_1_chunk_generator.html',1,'net::minecraft::world::gen']]],
  ['chunkgenstatus_597',['ChunkGenStatus',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_gen_status.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkholder_598',['ChunkHolder',['../classnet_1_1minecraft_1_1world_1_1server_1_1_chunk_holder.html',1,'net::minecraft::world::server']]],
  ['chunkinfodebugrenderer_599',['ChunkInfoDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_chunk_info_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['chunklightremovefix_600',['ChunkLightRemoveFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_light_remove_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkloader_601',['ChunkLoader',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_loader.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkloaderutil_602',['ChunkLoaderUtil',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_loader_util.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkmanager_603',['ChunkManager',['../classnet_1_1minecraft_1_1world_1_1server_1_1_chunk_manager.html',1,'net::minecraft::world::server']]],
  ['chunkpaletteformat_604',['ChunkPaletteFormat',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_palette_format.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkpos_605',['ChunkPos',['../classnet_1_1minecraft_1_1util_1_1math_1_1_chunk_pos.html',1,'net::minecraft::util::math']]],
  ['chunkprimer_606',['ChunkPrimer',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_607',['ChunkPrimerTickList',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_3c_20net_3a_3aminecraft_3a_3ablock_3a_3ablock_20_3e_608',['ChunkPrimerTickList&lt; net::minecraft::block::Block &gt;',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_3c_20net_3a_3aminecraft_3a_3afluid_3a_3afluid_20_3e_609',['ChunkPrimerTickList&lt; net::minecraft::fluid::Fluid &gt;',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerwrapper_610',['ChunkPrimerWrapper',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_wrapper.html',1,'net::minecraft::world::chunk']]],
  ['chunkrender_611',['ChunkRender',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_dispatcher_1_1_chunk_render.html',1,'net::minecraft::client::renderer::chunk::ChunkRenderDispatcher']]],
  ['chunkrendercache_612',['ChunkRenderCache',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_cache.html',1,'net::minecraft::client::renderer::chunk']]],
  ['chunkrenderdispatcher_613',['ChunkRenderDispatcher',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_dispatcher.html',1,'net::minecraft::client::renderer::chunk']]],
  ['chunksection_614',['ChunkSection',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_section.html',1,'net::minecraft::world::chunk']]],
  ['chunkserializer_615',['ChunkSerializer',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_serializer.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkstatus_616',['ChunkStatus',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_status.html',1,'net::minecraft::world::chunk']]],
  ['chunkstatusfix_617',['ChunkStatusFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_status_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkstatusfix2_618',['ChunkStatusFix2',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_status_fix2.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkstructurestemplaterenamefix_619',['ChunkStructuresTemplateRenameFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_structures_template_rename_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunktaskpriorityqueue_620',['ChunkTaskPriorityQueue',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_task_priority_queue.html',1,'net::minecraft::world::chunk']]],
  ['chunktaskpriorityqueuesorter_621',['ChunkTaskPriorityQueueSorter',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_task_priority_queue_sorter.html',1,'net::minecraft::world::chunk']]],
  ['cinputpacket_622',['CInputPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_input_packet.html',1,'net::minecraft::network::play::client']]],
  ['cjigsawblockgeneratepacket_623',['CJigsawBlockGeneratePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_jigsaw_block_generate_packet.html',1,'net::minecraft::network::play::client']]],
  ['ckeepalivepacket_624',['CKeepAlivePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_keep_alive_packet.html',1,'net::minecraft::network::play::client']]],
  ['classinheritancemultimap_625',['ClassInheritanceMultiMap',['../classnet_1_1minecraft_1_1util_1_1_class_inheritance_multi_map.html',1,'net::minecraft::util']]],
  ['classinheritancemultimap_3c_20net_3a_3aminecraft_3a_3aentity_3a_3aentity_20_3e_626',['ClassInheritanceMultiMap&lt; net::minecraft::entity::Entity &gt;',['../classnet_1_1minecraft_1_1util_1_1_class_inheritance_multi_map.html',1,'net::minecraft::util']]],
  ['clearcommand_627',['ClearCommand',['../classnet_1_1minecraft_1_1command_1_1impl_1_1_clear_command.html',1,'net::minecraft::command::impl']]],
  ['clearhurttask_628',['ClearHurtTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_clear_hurt_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['clickevent_629',['ClickEvent',['../classnet_1_1minecraft_1_1util_1_1text_1_1event_1_1_click_event.html',1,'net::minecraft::util::text::event']]],
  ['clicktype_630',['ClickType',['../enumnet_1_1minecraft_1_1inventory_1_1container_1_1_click_type.html',1,'net::minecraft::inventory::container']]],
  ['clientadvancementmanager_631',['ClientAdvancementManager',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_advancement_manager.html',1,'net::minecraft::client::multiplayer']]],
  ['clientbossinfo_632',['ClientBossInfo',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_client_boss_info.html',1,'net::minecraft::client::gui']]],
  ['clientbrandretriever_633',['ClientBrandRetriever',['../classnet_1_1minecraft_1_1client_1_1_client_brand_retriever.html',1,'net::minecraft::client']]],
  ['clientchunkprovider_634',['ClientChunkProvider',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_chunk_provider.html',1,'net::minecraft::client::multiplayer']]],
  ['clientgamesession_635',['ClientGameSession',['../classnet_1_1minecraft_1_1client_1_1_client_game_session.html',1,'net::minecraft::client']]],
  ['clienthandshakenethandler_636',['ClientHandshakeNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1handshake_1_1_client_handshake_net_handler.html',1,'net::minecraft::client::network::handshake']]],
  ['clientlanguagemap_637',['ClientLanguageMap',['../classnet_1_1minecraft_1_1client_1_1resources_1_1_client_language_map.html',1,'net::minecraft::client::resources']]],
  ['clientloginnethandler_638',['ClientLoginNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1login_1_1_client_login_net_handler.html',1,'net::minecraft::client::network::login']]],
  ['clientplayerentity_639',['ClientPlayerEntity',['../classnet_1_1minecraft_1_1client_1_1entity_1_1player_1_1_client_player_entity.html',1,'net::minecraft::client::entity::player']]],
  ['clientplaynethandler_640',['ClientPlayNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1play_1_1_client_play_net_handler.html',1,'net::minecraft::client::network::play']]],
  ['clientrecipebook_641',['ClientRecipeBook',['../classnet_1_1minecraft_1_1client_1_1util_1_1_client_recipe_book.html',1,'net::minecraft::client::util']]],
  ['clientsuggestionprovider_642',['ClientSuggestionProvider',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_suggestion_provider.html',1,'net::minecraft::client::multiplayer']]],
  ['clientthread_643',['ClientThread',['../classnet_1_1minecraft_1_1network_1_1rcon_1_1_client_thread.html',1,'net::minecraft::network::rcon']]],
  ['clientworld_644',['ClientWorld',['../classnet_1_1minecraft_1_1client_1_1world_1_1_client_world.html',1,'net::minecraft::client::world']]],
  ['climberpathnavigator_645',['ClimberPathNavigator',['../classnet_1_1minecraft_1_1pathfinding_1_1_climber_path_navigator.html',1,'net::minecraft::pathfinding']]],
  ['clipboardhelper_646',['ClipboardHelper',['../classnet_1_1minecraft_1_1client_1_1_clipboard_helper.html',1,'net::minecraft::client']]],
  ['clippinghelper_647',['ClippingHelper',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1culling_1_1_clipping_helper.html',1,'net::minecraft::client::renderer::culling']]],
  ['clockdifficultypacket_648',['CLockDifficultyPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_lock_difficulty_packet.html',1,'net::minecraft::network::play::client']]],
  ['cloginstartpacket_649',['CLoginStartPacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_login_start_packet.html',1,'net::minecraft::network::login::client']]],
  ['clonecommand_650',['CloneCommand',['../classnet_1_1minecraft_1_1command_1_1impl_1_1_clone_command.html',1,'net::minecraft::command::impl']]],
  ['closerealmsaction_651',['CloseRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_close_realms_action.html',1,'net::minecraft::realms::action']]],
  ['cloudoption_652',['CloudOption',['../enumnet_1_1minecraft_1_1client_1_1settings_1_1_cloud_option.html',1,'net::minecraft::client::settings']]],
  ['cloudparticle_653',['CloudParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_cloud_particle.html',1,'net::minecraft::client::particle']]],
  ['cmarkrecipeseenpacket_654',['CMarkRecipeSeenPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_mark_recipe_seen_packet.html',1,'net::minecraft::network::play::client']]],
  ['cmovevehiclepacket_655',['CMoveVehiclePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_move_vehicle_packet.html',1,'net::minecraft::network::play::client']]],
  ['coatcolors_656',['CoatColors',['../enumnet_1_1minecraft_1_1entity_1_1passive_1_1horse_1_1_coat_colors.html',1,'net::minecraft::entity::passive::horse']]],
  ['coattypes_657',['CoatTypes',['../enumnet_1_1minecraft_1_1entity_1_1passive_1_1horse_1_1_coat_types.html',1,'net::minecraft::entity::passive::horse']]],
  ['cocoablock_658',['CocoaBlock',['../classnet_1_1minecraft_1_1block_1_1_cocoa_block.html',1,'net::minecraft::block']]],
  ['cocoatreedecorator_659',['CocoaTreeDecorator',['../classnet_1_1minecraft_1_1world_1_1gen_1_1treedecorator_1_1_cocoa_tree_decorator.html',1,'net::minecraft::world::gen::treedecorator']]],
  ['codentity_660',['CodEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1fish_1_1_cod_entity.html',1,'net::minecraft::entity::passive::fish']]],
  ['codmodel_661',['CodModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cod_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['codrenderer_662',['CodRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cod_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['collectionnbt_663',['CollectionNBT',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20bytenbt_20_3e_664',['CollectionNBT&lt; ByteNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20inbt_20_3e_665',['CollectionNBT&lt; INBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20intnbt_20_3e_666',['CollectionNBT&lt; IntNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20longnbt_20_3e_667',['CollectionNBT&lt; LongNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collisionboxdebugrenderer_668',['CollisionBoxDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_collision_box_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['color_669',['Color',['../classnet_1_1minecraft_1_1util_1_1text_1_1_color.html',1,'net::minecraft::util::text']]],
  ['colorargument_670',['ColorArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_color_argument.html',1,'net::minecraft::command::arguments']]],
  ['colorcache_671',['ColorCache',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1color_1_1_color_cache.html',1,'net::minecraft::client::renderer::color']]],
  ['colorhelper_672',['ColorHelper',['../classnet_1_1minecraft_1_1util_1_1_color_helper.html',1,'net::minecraft::util']]],
  ['colorlessshulkerentityfix_673',['ColorlessShulkerEntityFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_colorless_shulker_entity_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['colormaploader_674',['ColorMapLoader',['../classnet_1_1minecraft_1_1client_1_1resources_1_1_color_map_loader.html',1,'net::minecraft::client::resources']]],
  ['colorresolver_675',['ColorResolver',['../interfacenet_1_1minecraft_1_1world_1_1level_1_1_color_resolver.html',1,'net::minecraft::world::level']]],
  ['columnblockplacer_676',['ColumnBlockPlacer',['../classnet_1_1minecraft_1_1world_1_1gen_1_1blockplacer_1_1_column_block_placer.html',1,'net::minecraft::world::gen::blockplacer']]],
  ['columnconfig_677',['ColumnConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_column_config.html',1,'net::minecraft::world::gen::feature']]],
  ['columnfuzzedbiomemagnifier_678',['ColumnFuzzedBiomeMagnifier',['../enumnet_1_1minecraft_1_1world_1_1biome_1_1_column_fuzzed_biome_magnifier.html',1,'net::minecraft::world::biome']]],
  ['columnpos_679',['ColumnPos',['../classnet_1_1minecraft_1_1util_1_1math_1_1_column_pos.html',1,'net::minecraft::util::math']]],
  ['columnposargument_680',['ColumnPosArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_column_pos_argument.html',1,'net::minecraft::command::arguments']]],
  ['combatentry_681',['CombatEntry',['../classnet_1_1minecraft_1_1util_1_1_combat_entry.html',1,'net::minecraft::util']]],
  ['combatrules_682',['CombatRules',['../classnet_1_1minecraft_1_1util_1_1_combat_rules.html',1,'net::minecraft::util']]],
  ['combattracker_683',['CombatTracker',['../classnet_1_1minecraft_1_1util_1_1_combat_tracker.html',1,'net::minecraft::util']]],
  ['commandblockblock_684',['CommandBlockBlock',['../classnet_1_1minecraft_1_1block_1_1_command_block_block.html',1,'net::minecraft::block']]],
  ['commandblocklogic_685',['CommandBlockLogic',['../classnet_1_1minecraft_1_1tileentity_1_1_command_block_logic.html',1,'net::minecraft::tileentity']]],
  ['commandblockminecartentity_686',['CommandBlockMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_command_block_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['commandblockscreen_687',['CommandBlockScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_command_block_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['commandblocktileentity_688',['CommandBlockTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_command_block_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['commandexception_689',['CommandException',['../classnet_1_1minecraft_1_1command_1_1_command_exception.html',1,'net::minecraft::command']]],
  ['commands_690',['Commands',['../classnet_1_1minecraft_1_1command_1_1_commands.html',1,'net::minecraft::command']]],
  ['commandsource_691',['CommandSource',['../classnet_1_1minecraft_1_1command_1_1_command_source.html',1,'net::minecraft::command']]],
  ['commandsreport_692',['CommandsReport',['../classnet_1_1minecraft_1_1data_1_1_commands_report.html',1,'net::minecraft::data']]],
  ['commandstorage_693',['CommandStorage',['../classnet_1_1minecraft_1_1world_1_1storage_1_1_command_storage.html',1,'net::minecraft::world::storage']]],
  ['commandsuggestionhelper_694',['CommandSuggestionHelper',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_command_suggestion_helper.html',1,'net::minecraft::client::gui']]],
  ['comparatorblock_695',['ComparatorBlock',['../classnet_1_1minecraft_1_1block_1_1_comparator_block.html',1,'net::minecraft::block']]],
  ['comparatormode_696',['ComparatorMode',['../enumnet_1_1minecraft_1_1state_1_1properties_1_1_comparator_mode.html',1,'net::minecraft::state::properties']]],
  ['comparatortileentity_697',['ComparatorTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_comparator_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['compassitem_698',['CompassItem',['../classnet_1_1minecraft_1_1item_1_1_compass_item.html',1,'net::minecraft::item']]],
  ['completedtutorialstep_699',['CompletedTutorialStep',['../classnet_1_1minecraft_1_1client_1_1tutorial_1_1_completed_tutorial_step.html',1,'net::minecraft::client::tutorial']]],
  ['componentargument_700',['ComponentArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_component_argument.html',1,'net::minecraft::command::arguments']]],
  ['composterblock_701',['ComposterBlock',['../classnet_1_1minecraft_1_1block_1_1_composter_block.html',1,'net::minecraft::block']]],
  ['compoundnbt_702',['CompoundNBT',['../classnet_1_1minecraft_1_1nbt_1_1_compound_n_b_t.html',1,'net::minecraft::nbt']]],
  ['compressedstreamtools_703',['CompressedStreamTools',['../classnet_1_1minecraft_1_1nbt_1_1_compressed_stream_tools.html',1,'net::minecraft::nbt']]],
  ['concretepowderblock_704',['ConcretePowderBlock',['../classnet_1_1minecraft_1_1block_1_1_concrete_powder_block.html',1,'net::minecraft::block']]],
  ['conditionarrayparser_705',['ConditionArrayParser',['../classnet_1_1minecraft_1_1loot_1_1_condition_array_parser.html',1,'net::minecraft::loot']]],
  ['conditionarrayserializer_706',['ConditionArraySerializer',['../classnet_1_1minecraft_1_1loot_1_1_condition_array_serializer.html',1,'net::minecraft::loot']]],
  ['conduitblock_707',['ConduitBlock',['../classnet_1_1minecraft_1_1block_1_1_conduit_block.html',1,'net::minecraft::block']]],
  ['conduittileentity_708',['ConduitTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_conduit_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['conduittileentityrenderer_709',['ConduitTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_conduit_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['configuredcarver_710',['ConfiguredCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredcarver_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3aprobabilityconfig_20_3e_711',['ConfiguredCarver&lt; net::minecraft::world::gen::feature::ProbabilityConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredcarvers_712',['ConfiguredCarvers',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carvers.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredfeature_713',['ConfiguredFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3abasetreefeatureconfig_2c_20_3f_3e_714',['ConfiguredFeature&lt; net::minecraft::world::gen::feature::BaseTreeFeatureConfig, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3ahugefungusconfig_2c_20_3f_3e_715',['ConfiguredFeature&lt; net::minecraft::world::gen::feature::HugeFungusConfig, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_3f_2c_20_3f_3e_716',['ConfiguredFeature&lt;?, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredplacement_717',['ConfiguredPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3afeaturespreadconfig_20_3e_718',['ConfiguredPlacement&lt; net::minecraft::world::gen::feature::FeatureSpreadConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3aplacement_3a_3anoplacementconfig_20_3e_719',['ConfiguredPlacement&lt; net::minecraft::world::gen::placement::NoPlacementConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3aplacement_3a_3atopsolidrangeconfig_20_3e_720',['ConfiguredPlacement&lt; net::minecraft::world::gen::placement::TopSolidRangeConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_3f_3e_721',['ConfiguredPlacement&lt;?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredrandomfeaturelist_722',['ConfiguredRandomFeatureList',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_random_feature_list.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredsurfacebuilder_723',['ConfiguredSurfaceBuilder',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builder.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['configuredsurfacebuilder_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3asurfacebuilders_3a_3asurfacebuilderconfig_20_3e_724',['ConfiguredSurfaceBuilder&lt; net::minecraft::world::gen::surfacebuilders::SurfaceBuilderConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builder.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['configuredsurfacebuilders_725',['ConfiguredSurfaceBuilders',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builders.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['confirmbackupscreen_726',['ConfirmBackupScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_backup_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['confirmopenlinkscreen_727',['ConfirmOpenLinkScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_open_link_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['confirmscreen_728',['ConfirmScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['congregatetask_729',['CongregateTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_congregate_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['connectedtorealmsaction_730',['ConnectedToRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_connected_to_realms_action.html',1,'net::minecraft::realms::action']]],
  ['connectingscreen_731',['ConnectingScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_connecting_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['connectingtorealmsaction_732',['ConnectingToRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_connecting_to_realms_action.html',1,'net::minecraft::realms::action']]],
  ['constantrange_733',['ConstantRange',['../classnet_1_1minecraft_1_1loot_1_1_constant_range.html',1,'net::minecraft::loot']]],
  ['constructbeacontrigger_734',['ConstructBeaconTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_construct_beacon_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['consumeitemtrigger_735',['ConsumeItemTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_consume_item_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['container_736',['Container',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container.html',1,'net::minecraft::inventory::container']]],
  ['containerblock_737',['ContainerBlock',['../classnet_1_1minecraft_1_1block_1_1_container_block.html',1,'net::minecraft::block']]],
  ['containerminecartentity_738',['ContainerMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_container_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['containerscreen_739',['ContainerScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20beaconcontainer_20_3e_740',['ContainerScreen&lt; BeaconContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20brewingstandcontainer_20_3e_741',['ContainerScreen&lt; BrewingStandContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20cartographycontainer_20_3e_742',['ContainerScreen&lt; CartographyContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20chestcontainer_20_3e_743',['ContainerScreen&lt; ChestContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20dispensercontainer_20_3e_744',['ContainerScreen&lt; DispenserContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20enchantmentcontainer_20_3e_745',['ContainerScreen&lt; EnchantmentContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20grindstonecontainer_20_3e_746',['ContainerScreen&lt; GrindstoneContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20hoppercontainer_20_3e_747',['ContainerScreen&lt; HopperContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20horseinventorycontainer_20_3e_748',['ContainerScreen&lt; HorseInventoryContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20loomcontainer_20_3e_749',['ContainerScreen&lt; LoomContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20merchantcontainer_20_3e_750',['ContainerScreen&lt; MerchantContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20shulkerboxcontainer_20_3e_751',['ContainerScreen&lt; ShulkerBoxContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20stonecuttercontainer_20_3e_752',['ContainerScreen&lt; StonecutterContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20t_20_3e_753',['ContainerScreen&lt; T &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20workbenchcontainer_20_3e_754',['ContainerScreen&lt; WorkbenchContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containertype_755',['ContainerType',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3abeaconcontainer_20_3e_756',['ContainerType&lt; net::minecraft::inventory::container::BeaconContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ablastfurnacecontainer_20_3e_757',['ContainerType&lt; net::minecraft::inventory::container::BlastFurnaceContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3abrewingstandcontainer_20_3e_758',['ContainerType&lt; net::minecraft::inventory::container::BrewingStandContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3acartographycontainer_20_3e_759',['ContainerType&lt; net::minecraft::inventory::container::CartographyContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3achestcontainer_20_3e_760',['ContainerType&lt; net::minecraft::inventory::container::ChestContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3adispensercontainer_20_3e_761',['ContainerType&lt; net::minecraft::inventory::container::DispenserContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aenchantmentcontainer_20_3e_762',['ContainerType&lt; net::minecraft::inventory::container::EnchantmentContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3afurnacecontainer_20_3e_763',['ContainerType&lt; net::minecraft::inventory::container::FurnaceContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3agrindstonecontainer_20_3e_764',['ContainerType&lt; net::minecraft::inventory::container::GrindstoneContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ahoppercontainer_20_3e_765',['ContainerType&lt; net::minecraft::inventory::container::HopperContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3alecterncontainer_20_3e_766',['ContainerType&lt; net::minecraft::inventory::container::LecternContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aloomcontainer_20_3e_767',['ContainerType&lt; net::minecraft::inventory::container::LoomContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3amerchantcontainer_20_3e_768',['ContainerType&lt; net::minecraft::inventory::container::MerchantContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3arepaircontainer_20_3e_769',['ContainerType&lt; net::minecraft::inventory::container::RepairContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ashulkerboxcontainer_20_3e_770',['ContainerType&lt; net::minecraft::inventory::container::ShulkerBoxContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3asmithingtablecontainer_20_3e_771',['ContainerType&lt; net::minecraft::inventory::container::SmithingTableContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3asmokercontainer_20_3e_772',['ContainerType&lt; net::minecraft::inventory::container::SmokerContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3astonecuttercontainer_20_3e_773',['ContainerType&lt; net::minecraft::inventory::container::StonecutterContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aworkbenchcontainer_20_3e_774',['ContainerType&lt; net::minecraft::inventory::container::WorkbenchContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_3f_3e_775',['ContainerType&lt;?&gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['controlsscreen_776',['ControlsScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_controls_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['cookingrecipebuilder_777',['CookingRecipeBuilder',['../classnet_1_1minecraft_1_1data_1_1_cooking_recipe_builder.html',1,'net::minecraft::data']]],
  ['cookingrecipeserializer_778',['CookingRecipeSerializer',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3ablastingrecipe_20_3e_779',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::BlastingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3acampfirecookingrecipe_20_3e_780',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::CampfireCookingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3afurnacerecipe_20_3e_781',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::FurnaceRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3asmokingrecipe_20_3e_782',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::SmokingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_3f_3e_783',['CookingRecipeSerializer&lt;?&gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cooldowntracker_784',['CooldownTracker',['../classnet_1_1minecraft_1_1util_1_1_cooldown_tracker.html',1,'net::minecraft::util']]],
  ['copyblockstate_785',['CopyBlockState',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_block_state.html',1,'net::minecraft::loot::functions']]],
  ['copyname_786',['CopyName',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_name.html',1,'net::minecraft::loot::functions']]],
  ['copynbt_787',['CopyNbt',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_nbt.html',1,'net::minecraft::loot::functions']]],
  ['coralblock_788',['CoralBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_block.html',1,'net::minecraft::block']]],
  ['coralclawfeature_789',['CoralClawFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_claw_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralfanblock_790',['CoralFanBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_fan_block.html',1,'net::minecraft::block']]],
  ['coralfansrenamelist_791',['CoralFansRenameList',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_coral_fans_rename_list.html',1,'net::minecraft::util::datafix::fixes']]],
  ['coralfeature_792',['CoralFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralfinblock_793',['CoralFinBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_fin_block.html',1,'net::minecraft::block']]],
  ['coralmushroomfeature_794',['CoralMushroomFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_mushroom_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralplantblock_795',['CoralPlantBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_plant_block.html',1,'net::minecraft::block']]],
  ['coraltreefeature_796',['CoralTreeFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_tree_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralwallfanblock_797',['CoralWallFanBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_wall_fan_block.html',1,'net::minecraft::block']]],
  ['countextraplacement_798',['CountExtraPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_extra_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countmultilayerplacement_799',['CountMultilayerPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_multilayer_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countnoisebiasedplacement_800',['CountNoiseBiasedPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_noise_biased_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countnoiseplacement_801',['CountNoisePlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_noise_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countplacement_802',['CountPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['cowentity_803',['CowEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_cow_entity.html',1,'net::minecraft::entity::passive']]],
  ['cowmodel_804',['CowModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cow_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['cowrenderer_805',['CowRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cow_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['cpickitempacket_806',['CPickItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_pick_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cpingpacket_807',['CPingPacket',['../classnet_1_1minecraft_1_1network_1_1status_1_1client_1_1_c_ping_packet.html',1,'net::minecraft::network::status::client']]],
  ['cplacerecipepacket_808',['CPlaceRecipePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_place_recipe_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerabilitiespacket_809',['CPlayerAbilitiesPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_abilities_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerdiggingpacket_810',['CPlayerDiggingPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_digging_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerpacket_811',['CPlayerPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayertryuseitemonblockpacket_812',['CPlayerTryUseItemOnBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_try_use_item_on_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayertryuseitempacket_813',['CPlayerTryUseItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_try_use_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cqueryentitynbtpacket_814',['CQueryEntityNBTPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_query_entity_n_b_t_packet.html',1,'net::minecraft::network::play::client']]],
  ['cquerytileentitynbtpacket_815',['CQueryTileEntityNBTPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_query_tile_entity_n_b_t_packet.html',1,'net::minecraft::network::play::client']]],
  ['craftinginventory_816',['CraftingInventory',['../classnet_1_1minecraft_1_1inventory_1_1_crafting_inventory.html',1,'net::minecraft::inventory']]],
  ['craftingresultslot_817',['CraftingResultSlot',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_crafting_result_slot.html',1,'net::minecraft::inventory::container']]],
  ['craftingscreen_818',['CraftingScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_crafting_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['craftingtableblock_819',['CraftingTableBlock',['../classnet_1_1minecraft_1_1block_1_1_crafting_table_block.html',1,'net::minecraft::block']]],
  ['craftplanksstep_820',['CraftPlanksStep',['../classnet_1_1minecraft_1_1client_1_1tutorial_1_1_craft_planks_step.html',1,'net::minecraft::client::tutorial']]],
  ['craftresultinventory_821',['CraftResultInventory',['../classnet_1_1minecraft_1_1inventory_1_1_craft_result_inventory.html',1,'net::minecraft::inventory']]],
  ['crashreport_822',['CrashReport',['../classnet_1_1minecraft_1_1crash_1_1_crash_report.html',1,'net::minecraft::crash']]],
  ['crashreportcategory_823',['CrashReportCategory',['../classnet_1_1minecraft_1_1crash_1_1_crash_report_category.html',1,'net::minecraft::crash']]],
  ['createattributes_824',['createAttributes',['../classnet_1_1minecraft_1_1fluid_1_1_fluid.html#a9d2cb19fdd3df181e3f35db17d3a7d22',1,'net::minecraft::fluid::Fluid']]],
  ['createbabyvillagertask_825',['CreateBabyVillagerTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_create_baby_villager_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['createbuffetworldscreen_826',['CreateBuffetWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_buffet_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['createdelayedoptional_827',['createDelayedOptional',['../classnet_1_1minecraft_1_1tags_1_1_tag_registry.html#aa691403668bd30cdc089e5d26f022ef9',1,'net::minecraft::tags::TagRegistry']]],
  ['createdelayedtag_828',['createDelayedTag',['../classnet_1_1minecraft_1_1tags_1_1_tag_registry.html#a8ebe9c613e46728b1d24d0853ee4ba8d',1,'net::minecraft::tags::TagRegistry']]],
  ['createflatworldscreen_829',['CreateFlatWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_flat_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['createworldrealmsaction_830',['CreateWorldRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_create_world_realms_action.html',1,'net::minecraft::realms::action']]],
  ['createworldscreen_831',['CreateWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['creativecraftinglistener_832',['CreativeCraftingListener',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_creative_crafting_listener.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['creativescreen_833',['CreativeScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_creative_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['creativesettings_834',['CreativeSettings',['../classnet_1_1minecraft_1_1client_1_1settings_1_1_creative_settings.html',1,'net::minecraft::client::settings']]],
  ['creatureattribute_835',['CreatureAttribute',['../classnet_1_1minecraft_1_1entity_1_1_creature_attribute.html',1,'net::minecraft::entity']]],
  ['creatureentity_836',['CreatureEntity',['../classnet_1_1minecraft_1_1entity_1_1_creature_entity.html',1,'net::minecraft::entity']]],
  ['creeperchargelayer_837',['CreeperChargeLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_creeper_charge_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['creeperentity_838',['CreeperEntity',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_creeper_entity.html',1,'net::minecraft::entity::monster']]],
  ['creepermodel_839',['CreeperModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_creeper_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['creepermodel_3c_20net_3a_3aminecraft_3a_3aentity_3a_3amonster_3a_3acreeperentity_20_3e_840',['CreeperModel&lt; net::minecraft::entity::monster::CreeperEntity &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_creeper_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['creeperrenderer_841',['CreeperRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_creeper_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['creeperswellgoal_842',['CreeperSwellGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_creeper_swell_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['crenameitempacket_843',['CRenameItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_rename_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cresourcepackstatuspacket_844',['CResourcePackStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_resource_pack_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['criteriatriggers_845',['CriteriaTriggers',['../classnet_1_1minecraft_1_1advancements_1_1_criteria_triggers.html',1,'net::minecraft::advancements']]],
  ['criterion_846',['Criterion',['../classnet_1_1minecraft_1_1advancements_1_1_criterion.html',1,'net::minecraft::advancements']]],
  ['criterioninstance_847',['CriterionInstance',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_criterion_instance.html',1,'net::minecraft::advancements::criterion']]],
  ['criterionprogress_848',['CriterionProgress',['../classnet_1_1minecraft_1_1advancements_1_1_criterion_progress.html',1,'net::minecraft::advancements']]],
  ['critparticle_849',['CritParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_crit_particle.html',1,'net::minecraft::client::particle']]],
  ['cropsblock_850',['CropsBlock',['../classnet_1_1minecraft_1_1block_1_1_crops_block.html',1,'net::minecraft::block']]],
  ['crossbowitem_851',['CrossbowItem',['../classnet_1_1minecraft_1_1item_1_1_crossbow_item.html',1,'net::minecraft::item']]],
  ['crossedarmsitemlayer_852',['CrossedArmsItemLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_crossed_arms_item_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['crossedarmsitemlayer_3c_20t_2c_20witchmodel_3c_20t_20_3e_20_3e_853',['CrossedArmsItemLayer&lt; T, WitchModel&lt; T &gt; &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_crossed_arms_item_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['cryingobsidianblock_854',['CryingObsidianBlock',['../classnet_1_1minecraft_1_1block_1_1_crying_obsidian_block.html',1,'net::minecraft::block']]],
  ['cryptmanager_855',['CryptManager',['../classnet_1_1minecraft_1_1util_1_1_crypt_manager.html',1,'net::minecraft::util']]],
  ['cseenadvancementspacket_856',['CSeenAdvancementsPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_seen_advancements_packet.html',1,'net::minecraft::network::play::client']]],
  ['cselecttradepacket_857',['CSelectTradePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_select_trade_packet.html',1,'net::minecraft::network::play::client']]],
  ['cserverquerypacket_858',['CServerQueryPacket',['../classnet_1_1minecraft_1_1network_1_1status_1_1client_1_1_c_server_query_packet.html',1,'net::minecraft::network::status::client']]],
  ['csetdifficultypacket_859',['CSetDifficultyPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_set_difficulty_packet.html',1,'net::minecraft::network::play::client']]],
  ['cspectatepacket_860',['CSpectatePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_spectate_packet.html',1,'net::minecraft::network::play::client']]],
  ['csteerboatpacket_861',['CSteerBoatPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_steer_boat_packet.html',1,'net::minecraft::network::play::client']]],
  ['csvwriter_862',['CSVWriter',['../classnet_1_1minecraft_1_1util_1_1_c_s_v_writer.html',1,'net::minecraft::util']]],
  ['ctabcompletepacket_863',['CTabCompletePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_tab_complete_packet.html',1,'net::minecraft::network::play::client']]],
  ['cubecoordinateiterator_864',['CubeCoordinateIterator',['../classnet_1_1minecraft_1_1util_1_1math_1_1_cube_coordinate_iterator.html',1,'net::minecraft::util::math']]],
  ['cubicsampler_865',['CubicSampler',['../classnet_1_1minecraft_1_1util_1_1_cubic_sampler.html',1,'net::minecraft::util']]],
  ['cupdatebeaconpacket_866',['CUpdateBeaconPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_beacon_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatecommandblockpacket_867',['CUpdateCommandBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_command_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatejigsawblockpacket_868',['CUpdateJigsawBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_jigsaw_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdateminecartcommandblockpacket_869',['CUpdateMinecartCommandBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_minecart_command_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdaterecipebookstatuspacket_870',['CUpdateRecipeBookStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_recipe_book_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatesignpacket_871',['CUpdateSignPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_sign_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatestructureblockpacket_872',['CUpdateStructureBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_structure_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['curedzombievillagertrigger_873',['CuredZombieVillagerTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_cured_zombie_villager_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['currentdownparticle_874',['CurrentDownParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_current_down_particle.html',1,'net::minecraft::client::particle']]],
  ['cuseentitypacket_875',['CUseEntityPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_use_entity_packet.html',1,'net::minecraft::network::play::client']]],
  ['customizeskinscreen_876',['CustomizeSkinScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_customize_skin_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['customnamestringtocomponententity_877',['CustomNameStringToComponentEntity',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_entity.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customnamestringtocomponentfixtileentity_878',['CustomNameStringToComponentFixTileEntity',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_fix_tile_entity.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customnamestringtocomponentitem_879',['CustomNameStringToComponentItem',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_item.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customrecipebuilder_880',['CustomRecipeBuilder',['../classnet_1_1minecraft_1_1data_1_1_custom_recipe_builder.html',1,'net::minecraft::data']]],
  ['customserverbossinfo_881',['CustomServerBossInfo',['../classnet_1_1minecraft_1_1server_1_1_custom_server_boss_info.html',1,'net::minecraft::server']]],
  ['customserverbossinfomanager_882',['CustomServerBossInfoManager',['../classnet_1_1minecraft_1_1server_1_1_custom_server_boss_info_manager.html',1,'net::minecraft::server']]]
];
