var searchData=
[
  ['cachedblockinfo_5279',['CachedBlockInfo',['../classnet_1_1minecraft_1_1util_1_1_cached_block_info.html',1,'net::minecraft::util']]],
  ['cactusblock_5280',['CactusBlock',['../classnet_1_1minecraft_1_1block_1_1_cactus_block.html',1,'net::minecraft::block']]],
  ['cakeblock_5281',['CakeBlock',['../classnet_1_1minecraft_1_1block_1_1_cake_block.html',1,'net::minecraft::block']]],
  ['campfireblock_5282',['CampfireBlock',['../classnet_1_1minecraft_1_1block_1_1_campfire_block.html',1,'net::minecraft::block']]],
  ['campfirecookingrecipe_5283',['CampfireCookingRecipe',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_campfire_cooking_recipe.html',1,'net::minecraft::item::crafting']]],
  ['campfireparticle_5284',['CampfireParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_campfire_particle.html',1,'net::minecraft::client::particle']]],
  ['campfiretileentity_5285',['CampfireTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_campfire_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['campfiretileentityrenderer_5286',['CampfireTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_campfire_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['canimatehandpacket_5287',['CAnimateHandPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_animate_hand_packet.html',1,'net::minecraft::network::play::client']]],
  ['canyonworldcarver_5288',['CanyonWorldCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_canyon_world_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['capelayer_5289',['CapeLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_cape_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['carpetblock_5290',['CarpetBlock',['../classnet_1_1minecraft_1_1block_1_1_carpet_block.html',1,'net::minecraft::block']]],
  ['carrotblock_5291',['CarrotBlock',['../classnet_1_1minecraft_1_1block_1_1_carrot_block.html',1,'net::minecraft::block']]],
  ['cartographycontainer_5292',['CartographyContainer',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_cartography_container.html',1,'net::minecraft::inventory::container']]],
  ['cartographytableblock_5293',['CartographyTableBlock',['../classnet_1_1minecraft_1_1block_1_1_cartography_table_block.html',1,'net::minecraft::block']]],
  ['cartographytablescreen_5294',['CartographyTableScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_cartography_table_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['carvedpumpkinblock_5295',['CarvedPumpkinBlock',['../classnet_1_1minecraft_1_1block_1_1_carved_pumpkin_block.html',1,'net::minecraft::block']]],
  ['castingaspellgoal_5296',['CastingASpellGoal',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_spellcasting_illager_entity_1_1_casting_a_spell_goal.html',1,'net::minecraft::entity::monster::SpellcastingIllagerEntity']]],
  ['catcollarlayer_5297',['CatCollarLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_cat_collar_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['categoryentry_5298',['CategoryEntry',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1list_1_1_key_binding_list_1_1_category_entry.html',1,'net::minecraft::client::gui::widget::list::KeyBindingList']]],
  ['catentity_5299',['CatEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_cat_entity.html',1,'net::minecraft::entity::passive']]],
  ['catlieonbedgoal_5300',['CatLieOnBedGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_cat_lie_on_bed_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['catmodel_5301',['CatModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cat_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['catmodel_3c_20net_3a_3aminecraft_3a_3aentity_3a_3apassive_3a_3acatentity_20_3e_5302',['CatModel&lt; net::minecraft::entity::passive::CatEntity &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cat_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['catrenderer_5303',['CatRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cat_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['catsitonblockgoal_5304',['CatSitOnBlockGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_cat_sit_on_block_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['catspawner_5305',['CatSpawner',['../classnet_1_1minecraft_1_1world_1_1spawner_1_1_cat_spawner.html',1,'net::minecraft::world::spawner']]],
  ['cattypefix_5306',['CatTypeFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_cat_type_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['cauldronblock_5307',['CauldronBlock',['../classnet_1_1minecraft_1_1block_1_1_cauldron_block.html',1,'net::minecraft::block']]],
  ['cavedebugrenderer_5308',['CaveDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_cave_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['caveedge_5309',['CaveEdge',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_cave_edge.html',1,'net::minecraft::world::gen::placement']]],
  ['caveedgeconfig_5310',['CaveEdgeConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_cave_edge_config.html',1,'net::minecraft::world::gen::placement']]],
  ['cavespiderentity_5311',['CaveSpiderEntity',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_cave_spider_entity.html',1,'net::minecraft::entity::monster']]],
  ['cavespiderrenderer_5312',['CaveSpiderRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cave_spider_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['caveworldcarver_5313',['CaveWorldCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_cave_world_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['cchatmessagepacket_5314',['CChatMessagePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_chat_message_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclickwindowpacket_5315',['CClickWindowPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_click_window_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclientsettingspacket_5316',['CClientSettingsPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_client_settings_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclientstatuspacket_5317',['CClientStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_client_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['cclosewindowpacket_5318',['CCloseWindowPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_close_window_packet.html',1,'net::minecraft::network::play::client']]],
  ['cconfirmteleportpacket_5319',['CConfirmTeleportPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_confirm_teleport_packet.html',1,'net::minecraft::network::play::client']]],
  ['cconfirmtransactionpacket_5320',['CConfirmTransactionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_confirm_transaction_packet.html',1,'net::minecraft::network::play::client']]],
  ['ccreativeinventoryactionpacket_5321',['CCreativeInventoryActionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_creative_inventory_action_packet.html',1,'net::minecraft::network::play::client']]],
  ['ccustompayloadloginpacket_5322',['CCustomPayloadLoginPacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_custom_payload_login_packet.html',1,'net::minecraft::network::login::client']]],
  ['ccustompayloadpacket_5323',['CCustomPayloadPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_custom_payload_packet.html',1,'net::minecraft::network::play::client']]],
  ['ceditbookpacket_5324',['CEditBookPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_edit_book_packet.html',1,'net::minecraft::network::play::client']]],
  ['celebrateraidlossgoal_5325',['CelebrateRaidLossGoal',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_abstract_raider_entity_1_1_celebrate_raid_loss_goal.html',1,'net::minecraft::entity::monster::AbstractRaiderEntity']]],
  ['celebrateraidvictorytask_5326',['CelebrateRaidVictoryTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_celebrate_raid_victory_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['cenchantitempacket_5327',['CEnchantItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_enchant_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cencryptionresponsepacket_5328',['CEncryptionResponsePacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_encryption_response_packet.html',1,'net::minecraft::network::login::client']]],
  ['centityactionpacket_5329',['CEntityActionPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_entity_action_packet.html',1,'net::minecraft::network::play::client']]],
  ['chainblock_5330',['ChainBlock',['../classnet_1_1minecraft_1_1block_1_1_chain_block.html',1,'net::minecraft::block']]],
  ['chainedchunkstatuslistener_5331',['ChainedChunkStatusListener',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1listener_1_1_chained_chunk_status_listener.html',1,'net::minecraft::world::chunk::listener']]],
  ['chanceconfig_5332',['ChanceConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_chance_config.html',1,'net::minecraft::world::gen::placement']]],
  ['chanceplacement_5333',['ChancePlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_chance_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['chandshakepacket_5334',['CHandshakePacket',['../classnet_1_1minecraft_1_1network_1_1handshake_1_1client_1_1_c_handshake_packet.html',1,'net::minecraft::network::handshake::client']]],
  ['changedimensiontrigger_5335',['ChangeDimensionTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_change_dimension_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['changejobtask_5336',['ChangeJobTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_change_job_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['changepagebutton_5337',['ChangePageButton',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1button_1_1_change_page_button.html',1,'net::minecraft::client::gui::widget::button']]],
  ['channeledlightningtrigger_5338',['ChanneledLightningTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_channeled_lightning_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['channelingenchantment_5339',['ChannelingEnchantment',['../classnet_1_1minecraft_1_1enchantment_1_1_channeling_enchantment.html',1,'net::minecraft::enchantment']]],
  ['channelmanager_5340',['ChannelManager',['../classnet_1_1minecraft_1_1client_1_1audio_1_1_channel_manager.html',1,'net::minecraft::client::audio']]],
  ['charactermanager_5341',['CharacterManager',['../classnet_1_1minecraft_1_1util_1_1text_1_1_character_manager.html',1,'net::minecraft::util::text']]],
  ['chargingplayerphase_5342',['ChargingPlayerPhase',['../classnet_1_1minecraft_1_1entity_1_1boss_1_1dragon_1_1phase_1_1_charging_player_phase.html',1,'net::minecraft::entity::boss::dragon::phase']]],
  ['chatline_5343',['ChatLine',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_chat_line.html',1,'net::minecraft::client::gui']]],
  ['chatoptionsscreen_5344',['ChatOptionsScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_chat_options_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['chatscreen_5345',['ChatScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_chat_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['chattype_5346',['ChatType',['../enumnet_1_1minecraft_1_1util_1_1text_1_1_chat_type.html',1,'net::minecraft::util::text']]],
  ['chatvisibility_5347',['ChatVisibility',['../enumnet_1_1minecraft_1_1entity_1_1player_1_1_chat_visibility.html',1,'net::minecraft::entity::player']]],
  ['checkboxbutton_5348',['CheckboxButton',['../classnet_1_1minecraft_1_1client_1_1gui_1_1widget_1_1button_1_1_checkbox_button.html',1,'net::minecraft::client::gui::widget::button']]],
  ['checkerboardbiomeprovider_5349',['CheckerboardBiomeProvider',['../classnet_1_1minecraft_1_1world_1_1biome_1_1provider_1_1_checkerboard_biome_provider.html',1,'net::minecraft::world::biome::provider']]],
  ['chelditemchangepacket_5350',['CHeldItemChangePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_held_item_change_packet.html',1,'net::minecraft::network::play::client']]],
  ['chestblock_5351',['ChestBlock',['../classnet_1_1minecraft_1_1block_1_1_chest_block.html',1,'net::minecraft::block']]],
  ['chestcontainer_5352',['ChestContainer',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_chest_container.html',1,'net::minecraft::inventory::container']]],
  ['chestedhorserenderer_5353',['ChestedHorseRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_chested_horse_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['chestloottables_5354',['ChestLootTables',['../classnet_1_1minecraft_1_1data_1_1loot_1_1_chest_loot_tables.html',1,'net::minecraft::data::loot']]],
  ['chestminecartentity_5355',['ChestMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_chest_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['chestscreen_5356',['ChestScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_chest_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['chesttileentity_5357',['ChestTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_chest_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['chesttileentityrenderer_5358',['ChestTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_chest_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['chesttype_5359',['ChestType',['../enumnet_1_1minecraft_1_1state_1_1properties_1_1_chest_type.html',1,'net::minecraft::state::properties']]],
  ['chickenentity_5360',['ChickenEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_chicken_entity.html',1,'net::minecraft::entity::passive']]],
  ['chickenmodel_5361',['ChickenModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_chicken_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['chickenrenderer_5362',['ChickenRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_chicken_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['child_5363',['Child',['../classnet_1_1minecraft_1_1client_1_1gui_1_1recipebook_1_1_recipe_overlay_gui_1_1_recipe_button_widget_1_1_child.html',1,'net::minecraft::client::gui::recipebook::RecipeOverlayGui::RecipeButtonWidget']]],
  ['childfollownearestadulttask_5364',['ChildFollowNearestAdultTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_child_follow_nearest_adult_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['chorusflowerblock_5365',['ChorusFlowerBlock',['../classnet_1_1minecraft_1_1block_1_1_chorus_flower_block.html',1,'net::minecraft::block']]],
  ['chorusfruititem_5366',['ChorusFruitItem',['../classnet_1_1minecraft_1_1item_1_1_chorus_fruit_item.html',1,'net::minecraft::item']]],
  ['chorusplantblock_5367',['ChorusPlantBlock',['../classnet_1_1minecraft_1_1block_1_1_chorus_plant_block.html',1,'net::minecraft::block']]],
  ['chorusplantfeature_5368',['ChorusPlantFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_chorus_plant_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['chunk_5369',['Chunk',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk.html',1,'net::minecraft::world::chunk']]],
  ['chunkborderdebugrenderer_5370',['ChunkBorderDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_chunk_border_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['chunkdistancegraph_5371',['ChunkDistanceGraph',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_distance_graph.html',1,'net::minecraft::world::chunk']]],
  ['chunkgenerator_5372',['ChunkGenerator',['../classnet_1_1minecraft_1_1world_1_1gen_1_1_chunk_generator.html',1,'net::minecraft::world::gen']]],
  ['chunkgenstatus_5373',['ChunkGenStatus',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_gen_status.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkholder_5374',['ChunkHolder',['../classnet_1_1minecraft_1_1world_1_1server_1_1_chunk_holder.html',1,'net::minecraft::world::server']]],
  ['chunkinfodebugrenderer_5375',['ChunkInfoDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_chunk_info_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['chunklightremovefix_5376',['ChunkLightRemoveFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_light_remove_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkloader_5377',['ChunkLoader',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_loader.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkloaderutil_5378',['ChunkLoaderUtil',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_loader_util.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkmanager_5379',['ChunkManager',['../classnet_1_1minecraft_1_1world_1_1server_1_1_chunk_manager.html',1,'net::minecraft::world::server']]],
  ['chunkpaletteformat_5380',['ChunkPaletteFormat',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_palette_format.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkpos_5381',['ChunkPos',['../classnet_1_1minecraft_1_1util_1_1math_1_1_chunk_pos.html',1,'net::minecraft::util::math']]],
  ['chunkprimer_5382',['ChunkPrimer',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_5383',['ChunkPrimerTickList',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_3c_20net_3a_3aminecraft_3a_3ablock_3a_3ablock_20_3e_5384',['ChunkPrimerTickList&lt; net::minecraft::block::Block &gt;',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerticklist_3c_20net_3a_3aminecraft_3a_3afluid_3a_3afluid_20_3e_5385',['ChunkPrimerTickList&lt; net::minecraft::fluid::Fluid &gt;',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_tick_list.html',1,'net::minecraft::world::chunk']]],
  ['chunkprimerwrapper_5386',['ChunkPrimerWrapper',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_primer_wrapper.html',1,'net::minecraft::world::chunk']]],
  ['chunkrender_5387',['ChunkRender',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_dispatcher_1_1_chunk_render.html',1,'net::minecraft::client::renderer::chunk::ChunkRenderDispatcher']]],
  ['chunkrendercache_5388',['ChunkRenderCache',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_cache.html',1,'net::minecraft::client::renderer::chunk']]],
  ['chunkrenderdispatcher_5389',['ChunkRenderDispatcher',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1chunk_1_1_chunk_render_dispatcher.html',1,'net::minecraft::client::renderer::chunk']]],
  ['chunksection_5390',['ChunkSection',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_section.html',1,'net::minecraft::world::chunk']]],
  ['chunkserializer_5391',['ChunkSerializer',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1storage_1_1_chunk_serializer.html',1,'net::minecraft::world::chunk::storage']]],
  ['chunkstatus_5392',['ChunkStatus',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_status.html',1,'net::minecraft::world::chunk']]],
  ['chunkstatusfix_5393',['ChunkStatusFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_status_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkstatusfix2_5394',['ChunkStatusFix2',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_status_fix2.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunkstructurestemplaterenamefix_5395',['ChunkStructuresTemplateRenameFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_chunk_structures_template_rename_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['chunktaskpriorityqueue_5396',['ChunkTaskPriorityQueue',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_task_priority_queue.html',1,'net::minecraft::world::chunk']]],
  ['chunktaskpriorityqueuesorter_5397',['ChunkTaskPriorityQueueSorter',['../classnet_1_1minecraft_1_1world_1_1chunk_1_1_chunk_task_priority_queue_sorter.html',1,'net::minecraft::world::chunk']]],
  ['cinputpacket_5398',['CInputPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_input_packet.html',1,'net::minecraft::network::play::client']]],
  ['cjigsawblockgeneratepacket_5399',['CJigsawBlockGeneratePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_jigsaw_block_generate_packet.html',1,'net::minecraft::network::play::client']]],
  ['ckeepalivepacket_5400',['CKeepAlivePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_keep_alive_packet.html',1,'net::minecraft::network::play::client']]],
  ['classinheritancemultimap_5401',['ClassInheritanceMultiMap',['../classnet_1_1minecraft_1_1util_1_1_class_inheritance_multi_map.html',1,'net::minecraft::util']]],
  ['classinheritancemultimap_3c_20net_3a_3aminecraft_3a_3aentity_3a_3aentity_20_3e_5402',['ClassInheritanceMultiMap&lt; net::minecraft::entity::Entity &gt;',['../classnet_1_1minecraft_1_1util_1_1_class_inheritance_multi_map.html',1,'net::minecraft::util']]],
  ['clearcommand_5403',['ClearCommand',['../classnet_1_1minecraft_1_1command_1_1impl_1_1_clear_command.html',1,'net::minecraft::command::impl']]],
  ['clearhurttask_5404',['ClearHurtTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_clear_hurt_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['clickevent_5405',['ClickEvent',['../classnet_1_1minecraft_1_1util_1_1text_1_1event_1_1_click_event.html',1,'net::minecraft::util::text::event']]],
  ['clicktype_5406',['ClickType',['../enumnet_1_1minecraft_1_1inventory_1_1container_1_1_click_type.html',1,'net::minecraft::inventory::container']]],
  ['clientadvancementmanager_5407',['ClientAdvancementManager',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_advancement_manager.html',1,'net::minecraft::client::multiplayer']]],
  ['clientbossinfo_5408',['ClientBossInfo',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_client_boss_info.html',1,'net::minecraft::client::gui']]],
  ['clientbrandretriever_5409',['ClientBrandRetriever',['../classnet_1_1minecraft_1_1client_1_1_client_brand_retriever.html',1,'net::minecraft::client']]],
  ['clientchunkprovider_5410',['ClientChunkProvider',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_chunk_provider.html',1,'net::minecraft::client::multiplayer']]],
  ['clientgamesession_5411',['ClientGameSession',['../classnet_1_1minecraft_1_1client_1_1_client_game_session.html',1,'net::minecraft::client']]],
  ['clienthandshakenethandler_5412',['ClientHandshakeNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1handshake_1_1_client_handshake_net_handler.html',1,'net::minecraft::client::network::handshake']]],
  ['clientlanguagemap_5413',['ClientLanguageMap',['../classnet_1_1minecraft_1_1client_1_1resources_1_1_client_language_map.html',1,'net::minecraft::client::resources']]],
  ['clientloginnethandler_5414',['ClientLoginNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1login_1_1_client_login_net_handler.html',1,'net::minecraft::client::network::login']]],
  ['clientplayerentity_5415',['ClientPlayerEntity',['../classnet_1_1minecraft_1_1client_1_1entity_1_1player_1_1_client_player_entity.html',1,'net::minecraft::client::entity::player']]],
  ['clientplaynethandler_5416',['ClientPlayNetHandler',['../classnet_1_1minecraft_1_1client_1_1network_1_1play_1_1_client_play_net_handler.html',1,'net::minecraft::client::network::play']]],
  ['clientrecipebook_5417',['ClientRecipeBook',['../classnet_1_1minecraft_1_1client_1_1util_1_1_client_recipe_book.html',1,'net::minecraft::client::util']]],
  ['clientsuggestionprovider_5418',['ClientSuggestionProvider',['../classnet_1_1minecraft_1_1client_1_1multiplayer_1_1_client_suggestion_provider.html',1,'net::minecraft::client::multiplayer']]],
  ['clientthread_5419',['ClientThread',['../classnet_1_1minecraft_1_1network_1_1rcon_1_1_client_thread.html',1,'net::minecraft::network::rcon']]],
  ['clientworld_5420',['ClientWorld',['../classnet_1_1minecraft_1_1client_1_1world_1_1_client_world.html',1,'net::minecraft::client::world']]],
  ['climberpathnavigator_5421',['ClimberPathNavigator',['../classnet_1_1minecraft_1_1pathfinding_1_1_climber_path_navigator.html',1,'net::minecraft::pathfinding']]],
  ['clipboardhelper_5422',['ClipboardHelper',['../classnet_1_1minecraft_1_1client_1_1_clipboard_helper.html',1,'net::minecraft::client']]],
  ['clippinghelper_5423',['ClippingHelper',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1culling_1_1_clipping_helper.html',1,'net::minecraft::client::renderer::culling']]],
  ['clockdifficultypacket_5424',['CLockDifficultyPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_lock_difficulty_packet.html',1,'net::minecraft::network::play::client']]],
  ['cloginstartpacket_5425',['CLoginStartPacket',['../classnet_1_1minecraft_1_1network_1_1login_1_1client_1_1_c_login_start_packet.html',1,'net::minecraft::network::login::client']]],
  ['clonecommand_5426',['CloneCommand',['../classnet_1_1minecraft_1_1command_1_1impl_1_1_clone_command.html',1,'net::minecraft::command::impl']]],
  ['closerealmsaction_5427',['CloseRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_close_realms_action.html',1,'net::minecraft::realms::action']]],
  ['cloudoption_5428',['CloudOption',['../enumnet_1_1minecraft_1_1client_1_1settings_1_1_cloud_option.html',1,'net::minecraft::client::settings']]],
  ['cloudparticle_5429',['CloudParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_cloud_particle.html',1,'net::minecraft::client::particle']]],
  ['cmarkrecipeseenpacket_5430',['CMarkRecipeSeenPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_mark_recipe_seen_packet.html',1,'net::minecraft::network::play::client']]],
  ['cmovevehiclepacket_5431',['CMoveVehiclePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_move_vehicle_packet.html',1,'net::minecraft::network::play::client']]],
  ['coatcolors_5432',['CoatColors',['../enumnet_1_1minecraft_1_1entity_1_1passive_1_1horse_1_1_coat_colors.html',1,'net::minecraft::entity::passive::horse']]],
  ['coattypes_5433',['CoatTypes',['../enumnet_1_1minecraft_1_1entity_1_1passive_1_1horse_1_1_coat_types.html',1,'net::minecraft::entity::passive::horse']]],
  ['cocoablock_5434',['CocoaBlock',['../classnet_1_1minecraft_1_1block_1_1_cocoa_block.html',1,'net::minecraft::block']]],
  ['cocoatreedecorator_5435',['CocoaTreeDecorator',['../classnet_1_1minecraft_1_1world_1_1gen_1_1treedecorator_1_1_cocoa_tree_decorator.html',1,'net::minecraft::world::gen::treedecorator']]],
  ['codentity_5436',['CodEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1fish_1_1_cod_entity.html',1,'net::minecraft::entity::passive::fish']]],
  ['codmodel_5437',['CodModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cod_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['codrenderer_5438',['CodRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cod_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['collectionnbt_5439',['CollectionNBT',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20bytenbt_20_3e_5440',['CollectionNBT&lt; ByteNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20inbt_20_3e_5441',['CollectionNBT&lt; INBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20intnbt_20_3e_5442',['CollectionNBT&lt; IntNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collectionnbt_3c_20longnbt_20_3e_5443',['CollectionNBT&lt; LongNBT &gt;',['../classnet_1_1minecraft_1_1nbt_1_1_collection_n_b_t.html',1,'net::minecraft::nbt']]],
  ['collisionboxdebugrenderer_5444',['CollisionBoxDebugRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1debug_1_1_collision_box_debug_renderer.html',1,'net::minecraft::client::renderer::debug']]],
  ['color_5445',['Color',['../classnet_1_1minecraft_1_1util_1_1text_1_1_color.html',1,'net::minecraft::util::text']]],
  ['colorargument_5446',['ColorArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_color_argument.html',1,'net::minecraft::command::arguments']]],
  ['colorcache_5447',['ColorCache',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1color_1_1_color_cache.html',1,'net::minecraft::client::renderer::color']]],
  ['colorhelper_5448',['ColorHelper',['../classnet_1_1minecraft_1_1util_1_1_color_helper.html',1,'net::minecraft::util']]],
  ['colorlessshulkerentityfix_5449',['ColorlessShulkerEntityFix',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_colorless_shulker_entity_fix.html',1,'net::minecraft::util::datafix::fixes']]],
  ['colormaploader_5450',['ColorMapLoader',['../classnet_1_1minecraft_1_1client_1_1resources_1_1_color_map_loader.html',1,'net::minecraft::client::resources']]],
  ['colorresolver_5451',['ColorResolver',['../interfacenet_1_1minecraft_1_1world_1_1level_1_1_color_resolver.html',1,'net::minecraft::world::level']]],
  ['columnblockplacer_5452',['ColumnBlockPlacer',['../classnet_1_1minecraft_1_1world_1_1gen_1_1blockplacer_1_1_column_block_placer.html',1,'net::minecraft::world::gen::blockplacer']]],
  ['columnconfig_5453',['ColumnConfig',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_column_config.html',1,'net::minecraft::world::gen::feature']]],
  ['columnfuzzedbiomemagnifier_5454',['ColumnFuzzedBiomeMagnifier',['../enumnet_1_1minecraft_1_1world_1_1biome_1_1_column_fuzzed_biome_magnifier.html',1,'net::minecraft::world::biome']]],
  ['columnpos_5455',['ColumnPos',['../classnet_1_1minecraft_1_1util_1_1math_1_1_column_pos.html',1,'net::minecraft::util::math']]],
  ['columnposargument_5456',['ColumnPosArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_column_pos_argument.html',1,'net::minecraft::command::arguments']]],
  ['combatentry_5457',['CombatEntry',['../classnet_1_1minecraft_1_1util_1_1_combat_entry.html',1,'net::minecraft::util']]],
  ['combatrules_5458',['CombatRules',['../classnet_1_1minecraft_1_1util_1_1_combat_rules.html',1,'net::minecraft::util']]],
  ['combattracker_5459',['CombatTracker',['../classnet_1_1minecraft_1_1util_1_1_combat_tracker.html',1,'net::minecraft::util']]],
  ['commandblockblock_5460',['CommandBlockBlock',['../classnet_1_1minecraft_1_1block_1_1_command_block_block.html',1,'net::minecraft::block']]],
  ['commandblocklogic_5461',['CommandBlockLogic',['../classnet_1_1minecraft_1_1tileentity_1_1_command_block_logic.html',1,'net::minecraft::tileentity']]],
  ['commandblockminecartentity_5462',['CommandBlockMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_command_block_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['commandblockscreen_5463',['CommandBlockScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_command_block_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['commandblocktileentity_5464',['CommandBlockTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_command_block_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['commandexception_5465',['CommandException',['../classnet_1_1minecraft_1_1command_1_1_command_exception.html',1,'net::minecraft::command']]],
  ['commands_5466',['Commands',['../classnet_1_1minecraft_1_1command_1_1_commands.html',1,'net::minecraft::command']]],
  ['commandsource_5467',['CommandSource',['../classnet_1_1minecraft_1_1command_1_1_command_source.html',1,'net::minecraft::command']]],
  ['commandsreport_5468',['CommandsReport',['../classnet_1_1minecraft_1_1data_1_1_commands_report.html',1,'net::minecraft::data']]],
  ['commandstorage_5469',['CommandStorage',['../classnet_1_1minecraft_1_1world_1_1storage_1_1_command_storage.html',1,'net::minecraft::world::storage']]],
  ['commandsuggestionhelper_5470',['CommandSuggestionHelper',['../classnet_1_1minecraft_1_1client_1_1gui_1_1_command_suggestion_helper.html',1,'net::minecraft::client::gui']]],
  ['comparatorblock_5471',['ComparatorBlock',['../classnet_1_1minecraft_1_1block_1_1_comparator_block.html',1,'net::minecraft::block']]],
  ['comparatormode_5472',['ComparatorMode',['../enumnet_1_1minecraft_1_1state_1_1properties_1_1_comparator_mode.html',1,'net::minecraft::state::properties']]],
  ['comparatortileentity_5473',['ComparatorTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_comparator_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['compassitem_5474',['CompassItem',['../classnet_1_1minecraft_1_1item_1_1_compass_item.html',1,'net::minecraft::item']]],
  ['completedtutorialstep_5475',['CompletedTutorialStep',['../classnet_1_1minecraft_1_1client_1_1tutorial_1_1_completed_tutorial_step.html',1,'net::minecraft::client::tutorial']]],
  ['componentargument_5476',['ComponentArgument',['../classnet_1_1minecraft_1_1command_1_1arguments_1_1_component_argument.html',1,'net::minecraft::command::arguments']]],
  ['composterblock_5477',['ComposterBlock',['../classnet_1_1minecraft_1_1block_1_1_composter_block.html',1,'net::minecraft::block']]],
  ['compoundnbt_5478',['CompoundNBT',['../classnet_1_1minecraft_1_1nbt_1_1_compound_n_b_t.html',1,'net::minecraft::nbt']]],
  ['compressedstreamtools_5479',['CompressedStreamTools',['../classnet_1_1minecraft_1_1nbt_1_1_compressed_stream_tools.html',1,'net::minecraft::nbt']]],
  ['concretepowderblock_5480',['ConcretePowderBlock',['../classnet_1_1minecraft_1_1block_1_1_concrete_powder_block.html',1,'net::minecraft::block']]],
  ['conditionarrayparser_5481',['ConditionArrayParser',['../classnet_1_1minecraft_1_1loot_1_1_condition_array_parser.html',1,'net::minecraft::loot']]],
  ['conditionarrayserializer_5482',['ConditionArraySerializer',['../classnet_1_1minecraft_1_1loot_1_1_condition_array_serializer.html',1,'net::minecraft::loot']]],
  ['conduitblock_5483',['ConduitBlock',['../classnet_1_1minecraft_1_1block_1_1_conduit_block.html',1,'net::minecraft::block']]],
  ['conduittileentity_5484',['ConduitTileEntity',['../classnet_1_1minecraft_1_1tileentity_1_1_conduit_tile_entity.html',1,'net::minecraft::tileentity']]],
  ['conduittileentityrenderer_5485',['ConduitTileEntityRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1tileentity_1_1_conduit_tile_entity_renderer.html',1,'net::minecraft::client::renderer::tileentity']]],
  ['configuredcarver_5486',['ConfiguredCarver',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredcarver_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3aprobabilityconfig_20_3e_5487',['ConfiguredCarver&lt; net::minecraft::world::gen::feature::ProbabilityConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carver.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredcarvers_5488',['ConfiguredCarvers',['../classnet_1_1minecraft_1_1world_1_1gen_1_1carver_1_1_configured_carvers.html',1,'net::minecraft::world::gen::carver']]],
  ['configuredfeature_5489',['ConfiguredFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3abasetreefeatureconfig_2c_20_3f_3e_5490',['ConfiguredFeature&lt; net::minecraft::world::gen::feature::BaseTreeFeatureConfig, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3ahugefungusconfig_2c_20_3f_3e_5491',['ConfiguredFeature&lt; net::minecraft::world::gen::feature::HugeFungusConfig, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredfeature_3c_3f_2c_20_3f_3e_5492',['ConfiguredFeature&lt;?, ?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredplacement_5493',['ConfiguredPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3afeature_3a_3afeaturespreadconfig_20_3e_5494',['ConfiguredPlacement&lt; net::minecraft::world::gen::feature::FeatureSpreadConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3aplacement_3a_3anoplacementconfig_20_3e_5495',['ConfiguredPlacement&lt; net::minecraft::world::gen::placement::NoPlacementConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3aplacement_3a_3atopsolidrangeconfig_20_3e_5496',['ConfiguredPlacement&lt; net::minecraft::world::gen::placement::TopSolidRangeConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredplacement_3c_3f_3e_5497',['ConfiguredPlacement&lt;?&gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_configured_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['configuredrandomfeaturelist_5498',['ConfiguredRandomFeatureList',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_configured_random_feature_list.html',1,'net::minecraft::world::gen::feature']]],
  ['configuredsurfacebuilder_5499',['ConfiguredSurfaceBuilder',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builder.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['configuredsurfacebuilder_3c_20net_3a_3aminecraft_3a_3aworld_3a_3agen_3a_3asurfacebuilders_3a_3asurfacebuilderconfig_20_3e_5500',['ConfiguredSurfaceBuilder&lt; net::minecraft::world::gen::surfacebuilders::SurfaceBuilderConfig &gt;',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builder.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['configuredsurfacebuilders_5501',['ConfiguredSurfaceBuilders',['../classnet_1_1minecraft_1_1world_1_1gen_1_1surfacebuilders_1_1_configured_surface_builders.html',1,'net::minecraft::world::gen::surfacebuilders']]],
  ['confirmbackupscreen_5502',['ConfirmBackupScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_backup_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['confirmopenlinkscreen_5503',['ConfirmOpenLinkScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_open_link_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['confirmscreen_5504',['ConfirmScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_confirm_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['congregatetask_5505',['CongregateTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_congregate_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['connectedtorealmsaction_5506',['ConnectedToRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_connected_to_realms_action.html',1,'net::minecraft::realms::action']]],
  ['connectingscreen_5507',['ConnectingScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_connecting_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['connectingtorealmsaction_5508',['ConnectingToRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_connecting_to_realms_action.html',1,'net::minecraft::realms::action']]],
  ['constantrange_5509',['ConstantRange',['../classnet_1_1minecraft_1_1loot_1_1_constant_range.html',1,'net::minecraft::loot']]],
  ['constructbeacontrigger_5510',['ConstructBeaconTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_construct_beacon_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['consumeitemtrigger_5511',['ConsumeItemTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_consume_item_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['container_5512',['Container',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container.html',1,'net::minecraft::inventory::container']]],
  ['containerblock_5513',['ContainerBlock',['../classnet_1_1minecraft_1_1block_1_1_container_block.html',1,'net::minecraft::block']]],
  ['containerminecartentity_5514',['ContainerMinecartEntity',['../classnet_1_1minecraft_1_1entity_1_1item_1_1minecart_1_1_container_minecart_entity.html',1,'net::minecraft::entity::item::minecart']]],
  ['containerscreen_5515',['ContainerScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20beaconcontainer_20_3e_5516',['ContainerScreen&lt; BeaconContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20brewingstandcontainer_20_3e_5517',['ContainerScreen&lt; BrewingStandContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20cartographycontainer_20_3e_5518',['ContainerScreen&lt; CartographyContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20chestcontainer_20_3e_5519',['ContainerScreen&lt; ChestContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20dispensercontainer_20_3e_5520',['ContainerScreen&lt; DispenserContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20enchantmentcontainer_20_3e_5521',['ContainerScreen&lt; EnchantmentContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20grindstonecontainer_20_3e_5522',['ContainerScreen&lt; GrindstoneContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20hoppercontainer_20_3e_5523',['ContainerScreen&lt; HopperContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20horseinventorycontainer_20_3e_5524',['ContainerScreen&lt; HorseInventoryContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20loomcontainer_20_3e_5525',['ContainerScreen&lt; LoomContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20merchantcontainer_20_3e_5526',['ContainerScreen&lt; MerchantContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20shulkerboxcontainer_20_3e_5527',['ContainerScreen&lt; ShulkerBoxContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20stonecuttercontainer_20_3e_5528',['ContainerScreen&lt; StonecutterContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20t_20_3e_5529',['ContainerScreen&lt; T &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containerscreen_3c_20workbenchcontainer_20_3e_5530',['ContainerScreen&lt; WorkbenchContainer &gt;',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_container_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['containertype_5531',['ContainerType',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3abeaconcontainer_20_3e_5532',['ContainerType&lt; net::minecraft::inventory::container::BeaconContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ablastfurnacecontainer_20_3e_5533',['ContainerType&lt; net::minecraft::inventory::container::BlastFurnaceContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3abrewingstandcontainer_20_3e_5534',['ContainerType&lt; net::minecraft::inventory::container::BrewingStandContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3acartographycontainer_20_3e_5535',['ContainerType&lt; net::minecraft::inventory::container::CartographyContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3achestcontainer_20_3e_5536',['ContainerType&lt; net::minecraft::inventory::container::ChestContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3adispensercontainer_20_3e_5537',['ContainerType&lt; net::minecraft::inventory::container::DispenserContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aenchantmentcontainer_20_3e_5538',['ContainerType&lt; net::minecraft::inventory::container::EnchantmentContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3afurnacecontainer_20_3e_5539',['ContainerType&lt; net::minecraft::inventory::container::FurnaceContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3agrindstonecontainer_20_3e_5540',['ContainerType&lt; net::minecraft::inventory::container::GrindstoneContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ahoppercontainer_20_3e_5541',['ContainerType&lt; net::minecraft::inventory::container::HopperContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3alecterncontainer_20_3e_5542',['ContainerType&lt; net::minecraft::inventory::container::LecternContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aloomcontainer_20_3e_5543',['ContainerType&lt; net::minecraft::inventory::container::LoomContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3amerchantcontainer_20_3e_5544',['ContainerType&lt; net::minecraft::inventory::container::MerchantContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3arepaircontainer_20_3e_5545',['ContainerType&lt; net::minecraft::inventory::container::RepairContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3ashulkerboxcontainer_20_3e_5546',['ContainerType&lt; net::minecraft::inventory::container::ShulkerBoxContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3asmithingtablecontainer_20_3e_5547',['ContainerType&lt; net::minecraft::inventory::container::SmithingTableContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3asmokercontainer_20_3e_5548',['ContainerType&lt; net::minecraft::inventory::container::SmokerContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3astonecuttercontainer_20_3e_5549',['ContainerType&lt; net::minecraft::inventory::container::StonecutterContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_20net_3a_3aminecraft_3a_3ainventory_3a_3acontainer_3a_3aworkbenchcontainer_20_3e_5550',['ContainerType&lt; net::minecraft::inventory::container::WorkbenchContainer &gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['containertype_3c_3f_3e_5551',['ContainerType&lt;?&gt;',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_container_type.html',1,'net::minecraft::inventory::container']]],
  ['controlsscreen_5552',['ControlsScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_controls_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['cookingrecipebuilder_5553',['CookingRecipeBuilder',['../classnet_1_1minecraft_1_1data_1_1_cooking_recipe_builder.html',1,'net::minecraft::data']]],
  ['cookingrecipeserializer_5554',['CookingRecipeSerializer',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3ablastingrecipe_20_3e_5555',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::BlastingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3acampfirecookingrecipe_20_3e_5556',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::CampfireCookingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3afurnacerecipe_20_3e_5557',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::FurnaceRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_20net_3a_3aminecraft_3a_3aitem_3a_3acrafting_3a_3asmokingrecipe_20_3e_5558',['CookingRecipeSerializer&lt; net::minecraft::item::crafting::SmokingRecipe &gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cookingrecipeserializer_3c_3f_3e_5559',['CookingRecipeSerializer&lt;?&gt;',['../classnet_1_1minecraft_1_1item_1_1crafting_1_1_cooking_recipe_serializer.html',1,'net::minecraft::item::crafting']]],
  ['cooldowntracker_5560',['CooldownTracker',['../classnet_1_1minecraft_1_1util_1_1_cooldown_tracker.html',1,'net::minecraft::util']]],
  ['copyblockstate_5561',['CopyBlockState',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_block_state.html',1,'net::minecraft::loot::functions']]],
  ['copyname_5562',['CopyName',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_name.html',1,'net::minecraft::loot::functions']]],
  ['copynbt_5563',['CopyNbt',['../classnet_1_1minecraft_1_1loot_1_1functions_1_1_copy_nbt.html',1,'net::minecraft::loot::functions']]],
  ['coralblock_5564',['CoralBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_block.html',1,'net::minecraft::block']]],
  ['coralclawfeature_5565',['CoralClawFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_claw_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralfanblock_5566',['CoralFanBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_fan_block.html',1,'net::minecraft::block']]],
  ['coralfansrenamelist_5567',['CoralFansRenameList',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_coral_fans_rename_list.html',1,'net::minecraft::util::datafix::fixes']]],
  ['coralfeature_5568',['CoralFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralfinblock_5569',['CoralFinBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_fin_block.html',1,'net::minecraft::block']]],
  ['coralmushroomfeature_5570',['CoralMushroomFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_mushroom_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralplantblock_5571',['CoralPlantBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_plant_block.html',1,'net::minecraft::block']]],
  ['coraltreefeature_5572',['CoralTreeFeature',['../classnet_1_1minecraft_1_1world_1_1gen_1_1feature_1_1_coral_tree_feature.html',1,'net::minecraft::world::gen::feature']]],
  ['coralwallfanblock_5573',['CoralWallFanBlock',['../classnet_1_1minecraft_1_1block_1_1_coral_wall_fan_block.html',1,'net::minecraft::block']]],
  ['countextraplacement_5574',['CountExtraPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_extra_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countmultilayerplacement_5575',['CountMultilayerPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_multilayer_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countnoisebiasedplacement_5576',['CountNoiseBiasedPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_noise_biased_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countnoiseplacement_5577',['CountNoisePlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_noise_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['countplacement_5578',['CountPlacement',['../classnet_1_1minecraft_1_1world_1_1gen_1_1placement_1_1_count_placement.html',1,'net::minecraft::world::gen::placement']]],
  ['cowentity_5579',['CowEntity',['../classnet_1_1minecraft_1_1entity_1_1passive_1_1_cow_entity.html',1,'net::minecraft::entity::passive']]],
  ['cowmodel_5580',['CowModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_cow_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['cowrenderer_5581',['CowRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_cow_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['cpickitempacket_5582',['CPickItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_pick_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cpingpacket_5583',['CPingPacket',['../classnet_1_1minecraft_1_1network_1_1status_1_1client_1_1_c_ping_packet.html',1,'net::minecraft::network::status::client']]],
  ['cplacerecipepacket_5584',['CPlaceRecipePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_place_recipe_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerabilitiespacket_5585',['CPlayerAbilitiesPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_abilities_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerdiggingpacket_5586',['CPlayerDiggingPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_digging_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayerpacket_5587',['CPlayerPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayertryuseitemonblockpacket_5588',['CPlayerTryUseItemOnBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_try_use_item_on_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cplayertryuseitempacket_5589',['CPlayerTryUseItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_player_try_use_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cqueryentitynbtpacket_5590',['CQueryEntityNBTPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_query_entity_n_b_t_packet.html',1,'net::minecraft::network::play::client']]],
  ['cquerytileentitynbtpacket_5591',['CQueryTileEntityNBTPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_query_tile_entity_n_b_t_packet.html',1,'net::minecraft::network::play::client']]],
  ['craftinginventory_5592',['CraftingInventory',['../classnet_1_1minecraft_1_1inventory_1_1_crafting_inventory.html',1,'net::minecraft::inventory']]],
  ['craftingresultslot_5593',['CraftingResultSlot',['../classnet_1_1minecraft_1_1inventory_1_1container_1_1_crafting_result_slot.html',1,'net::minecraft::inventory::container']]],
  ['craftingscreen_5594',['CraftingScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_crafting_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['craftingtableblock_5595',['CraftingTableBlock',['../classnet_1_1minecraft_1_1block_1_1_crafting_table_block.html',1,'net::minecraft::block']]],
  ['craftplanksstep_5596',['CraftPlanksStep',['../classnet_1_1minecraft_1_1client_1_1tutorial_1_1_craft_planks_step.html',1,'net::minecraft::client::tutorial']]],
  ['craftresultinventory_5597',['CraftResultInventory',['../classnet_1_1minecraft_1_1inventory_1_1_craft_result_inventory.html',1,'net::minecraft::inventory']]],
  ['crashreport_5598',['CrashReport',['../classnet_1_1minecraft_1_1crash_1_1_crash_report.html',1,'net::minecraft::crash']]],
  ['crashreportcategory_5599',['CrashReportCategory',['../classnet_1_1minecraft_1_1crash_1_1_crash_report_category.html',1,'net::minecraft::crash']]],
  ['createbabyvillagertask_5600',['CreateBabyVillagerTask',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1brain_1_1task_1_1_create_baby_villager_task.html',1,'net::minecraft::entity::ai::brain::task']]],
  ['createbuffetworldscreen_5601',['CreateBuffetWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_buffet_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['createflatworldscreen_5602',['CreateFlatWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_flat_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['createworldrealmsaction_5603',['CreateWorldRealmsAction',['../classnet_1_1minecraft_1_1realms_1_1action_1_1_create_world_realms_action.html',1,'net::minecraft::realms::action']]],
  ['createworldscreen_5604',['CreateWorldScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_create_world_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['creativecraftinglistener_5605',['CreativeCraftingListener',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_creative_crafting_listener.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['creativescreen_5606',['CreativeScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1inventory_1_1_creative_screen.html',1,'net::minecraft::client::gui::screen::inventory']]],
  ['creativesettings_5607',['CreativeSettings',['../classnet_1_1minecraft_1_1client_1_1settings_1_1_creative_settings.html',1,'net::minecraft::client::settings']]],
  ['creatureattribute_5608',['CreatureAttribute',['../classnet_1_1minecraft_1_1entity_1_1_creature_attribute.html',1,'net::minecraft::entity']]],
  ['creatureentity_5609',['CreatureEntity',['../classnet_1_1minecraft_1_1entity_1_1_creature_entity.html',1,'net::minecraft::entity']]],
  ['creeperchargelayer_5610',['CreeperChargeLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_creeper_charge_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['creeperentity_5611',['CreeperEntity',['../classnet_1_1minecraft_1_1entity_1_1monster_1_1_creeper_entity.html',1,'net::minecraft::entity::monster']]],
  ['creepermodel_5612',['CreeperModel',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_creeper_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['creepermodel_3c_20net_3a_3aminecraft_3a_3aentity_3a_3amonster_3a_3acreeperentity_20_3e_5613',['CreeperModel&lt; net::minecraft::entity::monster::CreeperEntity &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1model_1_1_creeper_model.html',1,'net::minecraft::client::renderer::entity::model']]],
  ['creeperrenderer_5614',['CreeperRenderer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1_creeper_renderer.html',1,'net::minecraft::client::renderer::entity']]],
  ['creeperswellgoal_5615',['CreeperSwellGoal',['../classnet_1_1minecraft_1_1entity_1_1ai_1_1goal_1_1_creeper_swell_goal.html',1,'net::minecraft::entity::ai::goal']]],
  ['crenameitempacket_5616',['CRenameItemPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_rename_item_packet.html',1,'net::minecraft::network::play::client']]],
  ['cresourcepackstatuspacket_5617',['CResourcePackStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_resource_pack_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['criteriatriggers_5618',['CriteriaTriggers',['../classnet_1_1minecraft_1_1advancements_1_1_criteria_triggers.html',1,'net::minecraft::advancements']]],
  ['criterion_5619',['Criterion',['../classnet_1_1minecraft_1_1advancements_1_1_criterion.html',1,'net::minecraft::advancements']]],
  ['criterioninstance_5620',['CriterionInstance',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_criterion_instance.html',1,'net::minecraft::advancements::criterion']]],
  ['criterionprogress_5621',['CriterionProgress',['../classnet_1_1minecraft_1_1advancements_1_1_criterion_progress.html',1,'net::minecraft::advancements']]],
  ['critparticle_5622',['CritParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_crit_particle.html',1,'net::minecraft::client::particle']]],
  ['cropsblock_5623',['CropsBlock',['../classnet_1_1minecraft_1_1block_1_1_crops_block.html',1,'net::minecraft::block']]],
  ['crossbowitem_5624',['CrossbowItem',['../classnet_1_1minecraft_1_1item_1_1_crossbow_item.html',1,'net::minecraft::item']]],
  ['crossedarmsitemlayer_5625',['CrossedArmsItemLayer',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_crossed_arms_item_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['crossedarmsitemlayer_3c_20t_2c_20witchmodel_3c_20t_20_3e_20_3e_5626',['CrossedArmsItemLayer&lt; T, WitchModel&lt; T &gt; &gt;',['../classnet_1_1minecraft_1_1client_1_1renderer_1_1entity_1_1layers_1_1_crossed_arms_item_layer.html',1,'net::minecraft::client::renderer::entity::layers']]],
  ['cryingobsidianblock_5627',['CryingObsidianBlock',['../classnet_1_1minecraft_1_1block_1_1_crying_obsidian_block.html',1,'net::minecraft::block']]],
  ['cryptmanager_5628',['CryptManager',['../classnet_1_1minecraft_1_1util_1_1_crypt_manager.html',1,'net::minecraft::util']]],
  ['cseenadvancementspacket_5629',['CSeenAdvancementsPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_seen_advancements_packet.html',1,'net::minecraft::network::play::client']]],
  ['cselecttradepacket_5630',['CSelectTradePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_select_trade_packet.html',1,'net::minecraft::network::play::client']]],
  ['cserverquerypacket_5631',['CServerQueryPacket',['../classnet_1_1minecraft_1_1network_1_1status_1_1client_1_1_c_server_query_packet.html',1,'net::minecraft::network::status::client']]],
  ['csetdifficultypacket_5632',['CSetDifficultyPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_set_difficulty_packet.html',1,'net::minecraft::network::play::client']]],
  ['cspectatepacket_5633',['CSpectatePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_spectate_packet.html',1,'net::minecraft::network::play::client']]],
  ['csteerboatpacket_5634',['CSteerBoatPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_steer_boat_packet.html',1,'net::minecraft::network::play::client']]],
  ['csvwriter_5635',['CSVWriter',['../classnet_1_1minecraft_1_1util_1_1_c_s_v_writer.html',1,'net::minecraft::util']]],
  ['ctabcompletepacket_5636',['CTabCompletePacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_tab_complete_packet.html',1,'net::minecraft::network::play::client']]],
  ['cubecoordinateiterator_5637',['CubeCoordinateIterator',['../classnet_1_1minecraft_1_1util_1_1math_1_1_cube_coordinate_iterator.html',1,'net::minecraft::util::math']]],
  ['cubicsampler_5638',['CubicSampler',['../classnet_1_1minecraft_1_1util_1_1_cubic_sampler.html',1,'net::minecraft::util']]],
  ['cupdatebeaconpacket_5639',['CUpdateBeaconPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_beacon_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatecommandblockpacket_5640',['CUpdateCommandBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_command_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatejigsawblockpacket_5641',['CUpdateJigsawBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_jigsaw_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdateminecartcommandblockpacket_5642',['CUpdateMinecartCommandBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_minecart_command_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdaterecipebookstatuspacket_5643',['CUpdateRecipeBookStatusPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_recipe_book_status_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatesignpacket_5644',['CUpdateSignPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_sign_packet.html',1,'net::minecraft::network::play::client']]],
  ['cupdatestructureblockpacket_5645',['CUpdateStructureBlockPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_update_structure_block_packet.html',1,'net::minecraft::network::play::client']]],
  ['curedzombievillagertrigger_5646',['CuredZombieVillagerTrigger',['../classnet_1_1minecraft_1_1advancements_1_1criterion_1_1_cured_zombie_villager_trigger.html',1,'net::minecraft::advancements::criterion']]],
  ['currentdownparticle_5647',['CurrentDownParticle',['../classnet_1_1minecraft_1_1client_1_1particle_1_1_current_down_particle.html',1,'net::minecraft::client::particle']]],
  ['cuseentitypacket_5648',['CUseEntityPacket',['../classnet_1_1minecraft_1_1network_1_1play_1_1client_1_1_c_use_entity_packet.html',1,'net::minecraft::network::play::client']]],
  ['customizeskinscreen_5649',['CustomizeSkinScreen',['../classnet_1_1minecraft_1_1client_1_1gui_1_1screen_1_1_customize_skin_screen.html',1,'net::minecraft::client::gui::screen']]],
  ['customnamestringtocomponententity_5650',['CustomNameStringToComponentEntity',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_entity.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customnamestringtocomponentfixtileentity_5651',['CustomNameStringToComponentFixTileEntity',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_fix_tile_entity.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customnamestringtocomponentitem_5652',['CustomNameStringToComponentItem',['../classnet_1_1minecraft_1_1util_1_1datafix_1_1fixes_1_1_custom_name_string_to_component_item.html',1,'net::minecraft::util::datafix::fixes']]],
  ['customrecipebuilder_5653',['CustomRecipeBuilder',['../classnet_1_1minecraft_1_1data_1_1_custom_recipe_builder.html',1,'net::minecraft::data']]],
  ['customserverbossinfo_5654',['CustomServerBossInfo',['../classnet_1_1minecraft_1_1server_1_1_custom_server_boss_info.html',1,'net::minecraft::server']]],
  ['customserverbossinfomanager_5655',['CustomServerBossInfoManager',['../classnet_1_1minecraft_1_1server_1_1_custom_server_boss_info_manager.html',1,'net::minecraft::server']]]
];
